# Generated by Django 5.1.4 on 2025-01-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeprofiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
